# tag::pendulum_config[]
# pendulum.yml
pendulumppo:
    env: Pendulum-v1  # <1>
    run: PPO  # <2>
    checkpoint_freq: 5  # <3>
    stop:
        episode_reward_mean: 800  # <4>
    config:
        lambda: 0.1  # <5>
        gamma: 0.95
        lr: 0.0003
        num_sgd_iter: 6
# end::pendulum_config[]